"""Abstract provider interfaces and mock implementations for Vision-Language Models (VLM)."""

from abc import ABC, abstractmethod
from typing import List, Optional
from pydantic import BaseModel, Field
from evidence_ocr.providers.ocr import ProviderMetadata


class VLMRecoveryRequest(BaseModel):
    """Targeted crop inspection request for low-confidence or disputed strokes."""

    crop_bytes: bytes = Field(description="Cropped image byte buffer of the ambiguous region")
    surrounding_context: str = Field(description="Transcription text of preceding and following line words")
    competing_candidates: List[str] = Field(description="Conflicting readings proposed by OCR engines")


class VLMResult(BaseModel):
    """Resolution proposal generated by a Vision-Language Model."""

    proposed_text: str = Field(description="Resolved text reading")
    reasoning: str = Field(description="Visual stroke analysis justification")
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence in resolution")
    metadata: ProviderMetadata = Field(description="Model metadata and version")


class BaseVLMProvider(ABC):
    """Abstract interface for external Vision-Language Model visual recovery."""

    @abstractmethod
    def get_metadata(self) -> ProviderMetadata:
        """Return provider and versioning metadata."""
        pass

    @abstractmethod
    async def inspect_crop(self, request: VLMRecoveryRequest) -> VLMResult:
        """Inspect cropped region and provide evidence-grounded reading."""
        pass


class MockVLMProvider(BaseVLMProvider):
    """Mock VLM provider for contract tests."""

    def __init__(self, model_version: str = "mock-vlm-v1") -> None:
        self.version = model_version

    def get_metadata(self) -> ProviderMetadata:
        return ProviderMetadata(
            provider_name="mock-vlm",
            model_identifier="mock-multimodal-inspector",
            model_version=self.version,
            parameters={"temperature": 0.0},
        )

    async def inspect_crop(self, request: VLMRecoveryRequest) -> VLMResult:
        chosen = request.competing_candidates[0] if request.competing_candidates else "recovered_token"
        return VLMResult(
            proposed_text=chosen,
            reasoning="Loop structure and stroke pressure align with top candidate.",
            confidence=0.88,
            metadata=self.get_metadata(),
        )
